version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Japan
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
    - "> 14.0.5, < 15"
  commit-message:
    prefix: deps
