name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: build
      env:
        DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag ${DOCKER_IMAGE} &&
        docker run ${DOCKER_IMAGE} version ||
        (echo -e "\e[31m[${GITHUB_WORKFLOW}] failed to build\e[m" && exit 1)

  hadolint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: hadolint
      run: |
        brew install hadolint
        hadolint ./Dockerfile
