name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}
    steps:

    - uses: actions/checkout@v1

    - name: Build
      run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE}

    - name: Print version
      run: docker run ${DOCKER_IMAGE} version

  hadolint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: brew install hadolint
    - run: hadolint ./Dockerfile
